### ISSUE TITLE
目前代码首次运行报错

### ISSUE THREAD

**Issue by iamcxds** [Geniucker/Deploy-ChatGPT-to-API#2]
至少首次运行会报错,
应该79行相关代码有关系
改回之前的 `with shelve.open('cache', writeback=True) as db:` 可以运行

**Comment by iamcxds** [comment]
此外测试404报错
![image](https://github.com/Geniucker/Deploy-ChatGPT-to-API/assets/10074835/b78dbcc9-03de-467d-9503-79672541e292)
使用的项目是
https://github.com/binary-husky/gpt_academic

**Comment by Geniucker** [comment]
> 至少首次运行会报错,
> 应该79行相关代码有关系
> 改回之前的 `with shelve.open('cache', writeback=True) as db:` 可以运行

可以给一下错误信息吗，顺便说一下是宿主机运行还是docker

**Comment by Geniucker** [comment]
> 此外测试404报错
> ![image](https://github.com/Geniucker/Deploy-ChatGPT-to-API/assets/10074835/b78dbcc9-03de-467d-9503-79672541e292)
> 使用的项目是
> https://github.com/binary-husky/gpt_academic

api填的地址有问题，路径是/v1/chat/completions

**Comment by Geniucker** [comment]
> 此外测试404报错 ![image](https://user-images.githubusercontent.com/10074835/245294419-b78dbcc9-03de-467d-9503-79672541e292.png) 使用的项目是 https://github.com/binary-husky/gpt_academic

![image](https://github.com/Geniucker/Deploy-ChatGPT-to-API/assets/61449208/adc9d5b3-79e0-44d6-a696-db8d17b4ace0)
配置应该是类似这样的

**Comment by Geniucker** [comment]
但是我今天又500了

**Comment by iamcxds** [comment]
> > 至少首次运行会报错,
> > 应该79行相关代码有关系
> > 改回之前的 `with shelve.open('cache', writeback=True) as db:` 可以运行
> 
> 可以给一下错误信息吗，顺便说一下是宿主机运行还是docker

主机运行
```
Traceback (most recent call last):
  File "/root/tools/Deploy-ChatGPT-to-API/run.py", line 305, in <module>
    access_token.append(i.refresh())
  File "/root/tools/Deploy-ChatGPT-to-API/run.py", line 120, in refresh
    self.make_cache()
  File "/root/tools/Deploy-ChatGPT-to-API/run.py", line 79, in make_cache
    with shelve.open('cache/cache.db', writeback=True) as db:
  File "/usr/lib/python3.10/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/usr/lib/python3.10/shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
  File "/usr/lib/python3.10/dbm/__init__.py", line 95, in open
    return mod.open(file, flag, mode)
_gdbm.error: [Errno 20] Not a directory: 'cache/cache.db'
Exception ignored in: <function Auth0.__del__ at 0x7fc5480ce290>
Traceback (most recent call last):
  File "/root/tools/Deploy-ChatGPT-to-API/run.py", line 77, in __del__
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 635, in post
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 573, in request
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 475, in prepare_request
  File "/usr/local/lib/python3.10/dist-packages/requests/cookies.py", line 556, in merge_cookies
  File "/usr/local/lib/python3.10/dist-packages/requests/cookies.py", line 362, in update
  File "/usr/lib/python3.10/copy.py", line 92, in copy
ImportError: sys.meta_path is None, Python is likely shutting down
```

**Comment by Geniucker** [comment]
现在应该已经修好了
git pull一下，如果有cache目录就先删掉，重新试一下
